### ISSUE TITLE
Phoronix test: GTX 970 only Maxwell GPU that doesn't work with GM2xx initial Nouveau patches..

### ISSUE THREAD

**Issue by oscarbg** [Gnurou/nouveau#14] opened 2016-03-31 14:50 UTC
Hi,
first sorry if it's not the correct way to report the bug..
but seems new Maxwell GTX970 isn't working with initial GM2xx support..
seems Phoronix tested a lot of Maxwell cards:
http://www.phoronix.com/scan.php?page=article&item=gtx-900-nouveau&num=1
and seems 970 is special as it says doesn't work but 980,980 Ti,960 all work:
"The graphics cards used for testing were the GeForce GTX 950, GTX 960, GTX 980, and GTX 980 Ti. The GeForce GTX 970 had to be left out of this comparison since upon the DRM/KMS driver loading, the display wouldn't light up with either DisplayPort or HDMI connections, but this problem wasn't experienced with the other graphics cards tested."

I also tested using:
*Ubuntu 15.10 x64 latest updates
*kernel 4.6rc1 from http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.6-rc1-wily/
*mesa 11.3.0dev build from 30march using oibaf ppa (compiles daily  builds)

Also note I have 970 GPU connected to 4k TV via HDMI 2.0 so expecting to get 3840x2160 60hz 4:4:4
Is HDMI2.0 4k@60 4:4:4 output working with initial patches?

thanks..

**Comment by Gnurou** [comment] 2016-04-01 01:35
Hi,

The proper place to report Nouveau issues is the freedesktop bug tracker. Actually there is already an issue opened for this:

https://bugs.freedesktop.org/show_bug.cgi?id=89664

I notice that it has been opened for a while but kind of stalled, maybe you will want to help pushing it forward? Note that the issue is display related, and thus has nothing to do with the recent addition of acceleration support (display is supported since last year on GM2xx).

The freedesktop bug suggests adding "nouveau.config=NvForcePost=1" to your kernel command line, maybe this will help?

Closing this issue - let's follow up on the freedesktop bug.

**Closed as completed by Gnurou** 2016-04-01 01:35 UTC
